/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PalaceRouteImport } from './routes/palace'
import { Route as StudioIdRouteImport } from './routes/studio.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PalaceRoute = PalaceRouteImport.update({
  id: '/palace',
  path: '/palace',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/studio/$id',
  path: '/studio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/ledger': typeof LedgerRoute
  '/market': typeof MarketRoute
  '/palace': typeof PalaceRoute
  '/studio/$id': typeof StudioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/ledger': typeof LedgerRoute
  '/market': typeof MarketRoute
  '/palace': typeof PalaceRoute
  '/studio/$id': typeof StudioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/ledger': typeof LedgerRoute
  '/market': typeof MarketRoute
  '/palace': typeof PalaceRoute
  '/studio/$id': typeof StudioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atlas' | '/ledger' | '/market' | '/palace' | '/studio/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atlas' | '/ledger' | '/market' | '/palace' | '/studio/$id'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/ledger'
    | '/market'
    | '/palace'
    | '/studio/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  LedgerRoute: typeof LedgerRoute
  MarketRoute: typeof MarketRoute
  PalaceRoute: typeof PalaceRoute
  StudioIdRoute: typeof StudioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palace': {
      id: '/palace'
      path: '/palace'
      fullPath: '/palace'
      preLoaderRoute: typeof PalaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/studio/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  LedgerRoute: LedgerRoute,
  MarketRoute: MarketRoute,
  PalaceRoute: PalaceRoute,
  StudioIdRoute: StudioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
